name: DBMS Validator

on:
  push:

jobs:
  check_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check DBMS Folder Exists
        run: |
          if [ ! -d "DBMS_PROJECT_2026" ]; then
            echo "ERROR: DBMS_PROJECT_2026 folder missing"
            exit 1
          fi

      - name: Success Message
        run: echo "Folder exists. Validation Passed."
